[versions]

androidDriver = "2.1.0"
kotlin = "2.2.0"
compose = "1.8.2"

koin = "4.1.0"
koinCompose = "4.1.0"
koinComposeMultiplatform = "4.1.0"

gradle = "8.12.0"
sqlDelight = " 2.1.0"
multiplatformSettings = "1.3.0"
core = "1.16.0"
jna = "5.17.0"
koalaplotCore = "0.9.0"
kotlinxCoroutinesSwing = "1.10.2"
kotlinxSerializationJson = "1.9.0"
kotlinxDateTime = "0.6.2"
material3WindowSizeClassMultiplatform = "0.5.0"
napier = "2.7.1"
core-library-desugaring = "2.1.5"
toast4j = "0.2.0"
compose-activity = "1.10.1"
spotless = "7.2.1"
accompanist-systemUIController = "0.36.0"
androidx-lifecycle = "2.9.1"
androidx-navigation = "2.9.0-beta03"

android-compileSdk = "36"
android-minSdk = "24"

[libraries]
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "androidDriver" }
core = { module = "androidx.core:core", version.ref = "core" }
coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "androidDriver" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplotCore" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }

kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesSwing" }
kotlinX-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }
material3-window-size-multiplatform = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "material3WindowSizeClassMultiplatform" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "androidDriver" }
primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "androidDriver" }
sqlDelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlinX-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "androidDriver" }
toast4j = { module = "de.mobanisto:toast4j", version.ref = "toast4j" }

core-library-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "core-library-desugaring" }
accompanist-systemUIController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemUIController" }

stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
nativeCocoapod = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinX-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqlDelight-plugin = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }